import DLayout from "@/components/dashboard/DLayout/DLayout";
import CategoryCreate from "@/components/filters/CategoryCreate";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Dashboard | course | category create",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <DLayout>
        <CategoryCreate isCreate={true} />
      </DLayout>
    </>
  );
};

export default page;
