import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Dashboard | Course List",
  description: "Generated by create next app",
};

const page = () => {
  return <div>page</div>;
};

export default page;
