import DLayout from "@/components/dashboard/DLayout/DLayout";
import LanguageCreate from "@/components/filters/LanguageCreate";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Dashboard | course | language create",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <DLayout>
        <LanguageCreate />
      </DLayout>
    </>
  );
};

export default page;
