import DLayout from "@/components/dashboard/DLayout/DLayout";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Dashboard | course | language list",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <DLayout>Language List</DLayout>
    </>
  );
};

export default page;
