import CourseCreate from "@/components/course/CourseCreate";
import DLayout from "@/components/dashboard/DLayout/DLayout";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Dashboard | Course Create",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <DLayout>
        <CourseCreate isCreate={false} />
      </DLayout>
    </>
  );
};

export default page;
