import CourseCreate from "@/components/course/CourseCreate";
import DLayout from "@/components/dashboard/DLayout/DLayout";
import AdminProtect from "@/hooks/useAdminProtect";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Dashboard | Course Create",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <AdminProtect>
        <DLayout>
          <CourseCreate isCreate={false} />
        </DLayout>
      </AdminProtect>
    </>
  );
};

export default page;
