import DLayout from "@/components/dashboard/DLayout/DLayout";
import AdminProtect from "@/hooks/useAdminProtect";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Dashboard | course | category list",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <AdminProtect>
        <DLayout>Category List</DLayout>
      </AdminProtect>
    </>
  );
};

export default page;
