import Signin from "@/components/auth/Signin";
import Signup from "@/components/auth/Signup";
import Layout from "@/components/layout/Layout";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Welcome to lms-v1 Signup page",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <Layout>
        <Signup />
      </Layout>
    </>
  );
};

export default page;
