import React from "react";
import DLayout from "@/components/dashboard/DLayout/DLayout";
import { Metadata } from "next";
import AdminProtect from "@/hooks/useAdminProtect";

export const metadata: Metadata = {
  title: "Welcome to lms-v1 dashboard",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <AdminProtect>
        <DLayout>
          <div>okdnf</div>
        </DLayout>
      </AdminProtect>
    </>
  );
};

export default page;
